### ISSUE TITLE
Missing resizeimage module in main.py

### ISSUE THREAD

**Issue by robertloredo** [Shedka/citiesatnight#1]
When running the main.py code on Python 3.7.3 I get the following error: 

```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from resizeimage import resizeimage
ModuleNotFoundError: No module named 'resizeimage'
```
Is there a module I need to install? I tried `pip install resizeimage` and it could not find one.

**Comment by hmfjx123** [comment]
HI!
I get the same problem. Have you already learn something about the missing module 'resizeimage' ?
I am looking forward to your reply.
`Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from resizeimage import resizeimage
ModuleNotFoundError: No module named 'resizeimage'`

**Comment by hmfjx123** [comment]
I have already solved the problem by using
`pip install --user python-resize-image`
I wish this can do a help
